name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:

  job_release:
    name: Create Release and Upload to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Build
      id: build
      run: |
        python setup.py build sdist bdist_wheel

    - name: Create GH release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        draft: true

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        verbose: true
